package Principal;
// Generated 20-feb-2021 18:09:36 by Hibernate Tools 5.4.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Club generated by hbm2java
 */
public class Club implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private String direccion;
	private Set competicions = new HashSet(0);

	public Club() {
	}

	public Club(String nombre) {
		this.nombre = nombre;
	}

	public Club(String nombre, String direccion, Set competicions) {
		this.nombre = nombre;
		this.direccion = direccion;
		this.competicions = competicions;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public Set getCompeticions() {
		return this.competicions;
	}

	public void setCompeticions(Set competicions) {
		this.competicions = competicions;
	}

}
