package Principal;
// Generated 20-feb-2021 18:09:36 by Hibernate Tools 5.4.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Competicion generated by hbm2java
 */
public class Competicion implements java.io.Serializable {

	private Integer id;
	private Club club;
	private String nombre;
	private Date fechaIni;
	private Date fechaFin;
	private int maxEquipGrupo;
	private Integer ascDesc;
	private String indivDobles;
	private Set grupos = new HashSet(0);
	private Set equipos = new HashSet(0);

	public Competicion() {
	}

	public Competicion(Club club, String nombre, Date fechaIni, Date fechaFin, int maxEquipGrupo, String indivDobles) {
		this.club = club;
		this.nombre = nombre;
		this.fechaIni = fechaIni;
		this.fechaFin = fechaFin;
		this.maxEquipGrupo = maxEquipGrupo;
		this.indivDobles = indivDobles;
	}

	public Competicion(Club club, String nombre, Date fechaIni, Date fechaFin, int maxEquipGrupo, Integer ascDesc,
			String indivDobles, Set grupos, Set equipos) {
		this.club = club;
		this.nombre = nombre;
		this.fechaIni = fechaIni;
		this.fechaFin = fechaFin;
		this.maxEquipGrupo = maxEquipGrupo;
		this.ascDesc = ascDesc;
		this.indivDobles = indivDobles;
		this.grupos = grupos;
		this.equipos = equipos;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Club getClub() {
		return this.club;
	}

	public void setClub(Club club) {
		this.club = club;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Date getFechaIni() {
		return this.fechaIni;
	}

	public void setFechaIni(Date fechaIni) {
		this.fechaIni = fechaIni;
	}

	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	public int getMaxEquipGrupo() {
		return this.maxEquipGrupo;
	}

	public void setMaxEquipGrupo(int maxEquipGrupo) {
		this.maxEquipGrupo = maxEquipGrupo;
	}

	public Integer getAscDesc() {
		return this.ascDesc;
	}

	public void setAscDesc(Integer ascDesc) {
		this.ascDesc = ascDesc;
	}

	public String getIndivDobles() {
		return this.indivDobles;
	}

	public void setIndivDobles(String indivDobles) {
		this.indivDobles = indivDobles;
	}

	public Set getGrupos() {
		return this.grupos;
	}

	public void setGrupos(Set grupos) {
		this.grupos = grupos;
	}

	public Set getEquipos() {
		return this.equipos;
	}

	public void setEquipos(Set equipos) {
		this.equipos = equipos;
	}

}
