package Principal;
// Generated 20-feb-2021 18:09:36 by Hibernate Tools 5.4.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Grupo generated by hbm2java
 */
public class Grupo implements java.io.Serializable {

	private Integer id;
	private Competicion competicion;
	private int orden;
	private String nombre;
	private Set equipos = new HashSet(0);
	private Set partidos = new HashSet(0);

	public Grupo() {
	}

	public Grupo(Competicion competicion, int orden, String nombre) {
		this.competicion = competicion;
		this.orden = orden;
		this.nombre = nombre;
	}

	public Grupo(Competicion competicion, int orden, String nombre, Set equipos, Set partidos) {
		this.competicion = competicion;
		this.orden = orden;
		this.nombre = nombre;
		this.equipos = equipos;
		this.partidos = partidos;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Competicion getCompeticion() {
		return this.competicion;
	}

	public void setCompeticion(Competicion competicion) {
		this.competicion = competicion;
	}

	public int getOrden() {
		return this.orden;
	}

	public void setOrden(int orden) {
		this.orden = orden;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getEquipos() {
		return this.equipos;
	}

	public void setEquipos(Set equipos) {
		this.equipos = equipos;
	}

	public Set getPartidos() {
		return this.partidos;
	}

	public void setPartidos(Set partidos) {
		this.partidos = partidos;
	}

}
