package Principal;
// Generated 20-feb-2021 18:09:36 by Hibernate Tools 5.4.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Jugador generated by hbm2java
 */
public class Jugador implements java.io.Serializable {

	private Integer id;
	private String email;
	private String nombre;
	private Date fechaNac;
	private Integer nivel;
	private Set equipos = new HashSet(0);

	public Jugador() {
	}

	public Jugador(String email, String nombre) {
		this.email = email;
		this.nombre = nombre;
	}

	public Jugador(String email, String nombre, Date fechaNac, Integer nivel, Set equipos) {
		this.email = email;
		this.nombre = nombre;
		this.fechaNac = fechaNac;
		this.nivel = nivel;
		this.equipos = equipos;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Date getFechaNac() {
		return this.fechaNac;
	}

	public void setFechaNac(Date fechaNac) {
		this.fechaNac = fechaNac;
	}

	public Integer getNivel() {
		return this.nivel;
	}

	public void setNivel(Integer nivel) {
		this.nivel = nivel;
	}

	public Set getEquipos() {
		return this.equipos;
	}

	public void setEquipos(Set equipos) {
		this.equipos = equipos;
	}

}
