package Principal;
// Generated 20-feb-2021 18:09:36 by Hibernate Tools 5.4.3.Final

/**
 * Set generated by hbm2java
 */
public class Set implements java.io.Serializable {

	private Integer id;
	private Equipo equipo;
	private Partido partido;
	private int orden;
	private int res1;
	private int res2;

	public Set() {
	}

	public Set(Equipo equipo, Partido partido, int orden, int res1, int res2) {
		this.equipo = equipo;
		this.partido = partido;
		this.orden = orden;
		this.res1 = res1;
		this.res2 = res2;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Equipo getEquipo() {
		return this.equipo;
	}

	public void setEquipo(Equipo equipo) {
		this.equipo = equipo;
	}

	public Partido getPartido() {
		return this.partido;
	}

	public void setPartido(Partido partido) {
		this.partido = partido;
	}

	public int getOrden() {
		return this.orden;
	}

	public void setOrden(int orden) {
		this.orden = orden;
	}

	public int getRes1() {
		return this.res1;
	}

	public void setRes1(int res1) {
		this.res1 = res1;
	}

	public int getRes2() {
		return this.res2;
	}

	public void setRes2(int res2) {
		this.res2 = res2;
	}

}
